"""Sandboxed Python execution — the analyst's 'hands' (SPEC §7).

The agent writes pandas/sklearn code; we run it in a fresh subprocess with the
dataset pre-loaded as `df`, a timeout, and result capture. The caller gets back
stdout plus the repr of a `result` variable if the code sets one.

ISOLATION BOUNDARY (be honest about it):
  v1 = a separate Python subprocess + wall-clock timeout. This prevents generated
  code from hanging the app and isolates crashes/state from the parent process.
  It does NOT yet restrict filesystem or network access — true confinement needs
  OS-level sandboxing (container + seccomp / restricted user), which is the
  hardening step in a later milestone. Do not run untrusted third-party code with
  this in production as-is; in Ledger the code is generated by our own prompted
  agent against a known dataset.

(An earlier version tried an import-allowlist hook; it was removed because it
blocked pandas/numpy's own internal lazy imports and gave only false security.)
"""
from __future__ import annotations

import subprocess
import sys
import tempfile
import textwrap
from dataclasses import dataclass
from pathlib import Path

_HARNESS = '''
import pandas as pd
import numpy as np

df = pd.read_csv({csv_path!r}, low_memory=False)
for _c in df.columns:
    if "date" in _c.lower():
        try:
            df[_c] = pd.to_datetime(df[_c])
        except Exception:
            pass

result = None
_ns = {{"df": df, "pd": pd, "np": np}}
try:
    exec(compile({code!r}, "<sandbox>", "exec"), _ns)
    result = _ns.get("result", None)
    print("\\n__RESULT__" + repr(result)[:4000])
except Exception as _e:
    print("__ERROR__" + repr(_e))
'''


@dataclass
class SandboxResult:
    ok: bool
    stdout: str
    result_repr: str | None
    error: str | None


def run_python(code: str, csv_path: str, *, timeout: int = 20) -> SandboxResult:
    """Execute `code` against the dataset at `csv_path` in an isolated subprocess.

    The dataset is available as `df`; assign to `result` to return a value.
    """
    harness = _HARNESS.format(csv_path=str(Path(csv_path).resolve()),
                              code=textwrap.dedent(code))
    with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as fh:
        fh.write(harness)
        script = fh.name
    try:
        proc = subprocess.run(
            [sys.executable, script],
            capture_output=True, text=True, timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return SandboxResult(False, "", None, f"timed out after {timeout}s")
    finally:
        Path(script).unlink(missing_ok=True)

    out = proc.stdout
    if "__ERROR__" in out:
        stdout, _, err = out.partition("__ERROR__")
        return SandboxResult(False, stdout.strip(), None, err.strip())
    result_repr = None
    if "__RESULT__" in out:
        out, _, result_repr = out.partition("__RESULT__")
    if proc.returncode != 0 and result_repr is None:
        return SandboxResult(False, out.strip(), None, proc.stderr.strip() or "non-zero exit")
    return SandboxResult(True, out.strip(), (result_repr or "").strip(), None)
